import { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useMemo } from "react";
import { trpc } from "../../../utils/trpc";
import { Input } from "@material-tailwind/react";
import PhotoCamera from "@mui/icons-material/PhotoCamera";
import IconButton from "@mui/material/IconButton";
import Select from "react-select";
import { Part } from "@prisma/client";
import { Donor } from "@prisma/client";
import { PartDetail } from "@prisma/client";


interface Options {
  label: string;
  value: string;
}

interface NestedOptions {
  label: string;
  options: Array<Options>;
}



const AddListing: NextPage = () => {
  const [title, setTitle] = React.useState<string>("");
  const [description, setDescription] = React.useState<string>("");
  const [condition, setCondition] = React.useState<string>("");
  const [price, setPrice] = React.useState<number>(0);
  const [weight, setWeight] = React.useState<number>(0);
  const [length, setLength] = React.useState<number>(0);
  const [width, setWidth] = React.useState<number>(0);
  const [height, setHeight] = React.useState<number>(0);
  const [images, setImages] = React.useState<Array<string>>([]);
  const [parts, setParts] = React.useState<Array<string>>([]);
  const [partOptions, setPartOptions] = React.useState<any>([]);

  const donors = trpc.donors.getAllWithParts.useQuery(undefined, {
    onSuccess: (data) => {
      console.log(data)
      const options = data.map((donor: any) => {
        return {
          label: donor.vin,
          options: donor.parts.map((part: any) => {
            return {
              label: `${part.partDetails.name} (${part.partDetails.partNo})`,
              value: part.id,
              tab: donor.vin
            }
          })
        }
      });
      setPartOptions(options);
    }
  })

  const saveListing = trpc.listings.createListing.useMutation();
  const uploadImage = trpc.listings.uploadListingImage.useMutation();
  const createImageRecord = trpc.images.createImageRecord.useMutation();

  const handleImageAttach = (e: any) => {
    Array.from(e.target.files).forEach((file: any) => {
      const reader = new FileReader();
      reader.onload = (onLoadEvent: any) => {
        setImages((imageState: any) => [
          ...imageState,
          onLoadEvent.target.result,
        ]);
      };
      reader.readAsDataURL(file);
    });
  };

  const onSave = async () => {
    const result = await saveListing.mutateAsync({
      title: title,
      description: description,
      condition: condition,
      price: price * 100,
      weight: weight * 1000,
      length: length * 10,
      width: width * 10,
      height: height * 10,
      parts: parts
    });
    const listingId = result.id;
    const imagePromises = images.map(async (image: string) => {
      const imageRes = await uploadImage.mutateAsync({
        image: image,
      });
      return createImageRecord.mutateAsync({
        listingId: listingId,
        url: imageRes.url,
      });
    });
    await Promise.all([...imagePromises]);
    console.log("finished");
    setTitle("");
    setDescription("");
    setCondition("");
    setPrice(0);
    setWeight(0);
    setLength(0);
    setWidth(0);
    setHeight(0);
    setImages([]);
  };

  return (
    <>
      <Head>
        <title>Create Listing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h- flex flex-col items-center justify-center bg-white">
        <div className="space-y-6 p-6">
          <div className="w-72">
            <Input
              value={title}
              label="Title"
              onChange={(e) => setTitle(e.target.value)}
            />
          </div>
          <div className="w-72">
            <Input
              value={description}
              label="Description"
              onChange={(e) => setDescription(e.target.value)}
            />
          </div>
          <div className="w-72">
            <Input
              value={condition}
              label="Condition"
              onChange={(e) => setCondition(e.target.value)}
            />
          </div>
          <div className="w-72">
            <Input
              value={price || undefined}
              type="number"
              label="Price"
              onChange={(e) => setPrice(Number(e.target.value))}
            />
          </div>
          <div className="w-72">
            <Input
              value={weight || undefined}
              type="number"
              label="Weight"
              onChange={(e) => setWeight(Number(e.target.value))}
            />
          </div>
          <div className="w-72">
            <Input
              value={length || undefined}
              type="number"
              label="Length"
              onChange={(e) => setLength(Number(e.target.value))}
            />
          </div>
          <div className="w-72">
            <Input
              value={width || undefined}
              type="number"
              label="Width"
              onChange={(e) => setWidth(Number(e.target.value))}
            />
          </div>
          <div className="w-72">
            <Input
              value={height || undefined}
              type="number"
              label="Height"
              onChange={(e) => setHeight(Number(e.target.value))}
            />
          </div>
          <div className="mb-6">
            <label className="mb-2 block text-sm font-medium text-gray-900 dark:text-white">
              Parts
            </label>
            <Select
              onChange={(e: any) => {
                setParts(e.map((part: Options) => part.value));
              }}
              isMulti
              options={partOptions}
              className="basic-multi-select"
              classNamePrefix="select"
              closeMenuOnSelect={false}
            />
          </div>
          <div className="flex items-center justify-between">
            <IconButton
              color="primary"
              aria-label="upload picture"
              component="label"
            >
              <input
                hidden
                accept="image/*"
                type="file"
                multiple={true}
                onChange={handleImageAttach}
              />
              <PhotoCamera />
            </IconButton>
            <p>{images.length} Photos attached</p>
          </div>
          <button onClick={onSave}>Create</button>
        </div>
      </main>
    </>
  );
};

export default AddListing;
