import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import TimeToLeaveIcon from "@mui/icons-material/TimeToLeave";
import BuildIcon from "@mui/icons-material/Build";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import Spacer from "../../../components/Spacer";

const Data: NextPage = () => {
  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      window.location.href = "/";
    },
  });



  return (
    <>
      <Head>
        <title>Data</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="flex items-center m-20">
          <Link
            href="/admin"
            className="mr-2 mb-2 w-fit rounded-lg border border-gray-800 px-5 py-2.5 text-center text-sm font-medium text-gray-900 hover:bg-gray-900 hover:text-white focus:outline-none focus:ring-4 focus:ring-gray-300 dark:border-gray-600 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white dark:focus:ring-gray-800"
          >
            {"<"}
          </Link>
          <Spacer amount="2" />
          <p className="text-xl">admin/data</p>
      </div>
          <Spacer amount="24" />
      <main className="flex min-h-screen w-full flex-col items-center">
        <section className="w-full bg-white py-10 sm:py-16 lg:py-24">
          <div className="mx-auto w-[50%] px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 gap-12 text-center sm:grid-cols-2 md:grid-cols-2 lg:gap-y-16">
              <Link
                href="/admin/data/cars"
                className="w-full cursor-pointer duration-150 ease-linear hover:scale-[1.2]"
              >
                <div className="relative mx-auto flex items-center justify-center">
                  <TimeToLeaveIcon fontSize="large" />
                </div>
                <h3 className="mt-8 text-lg font-semibold text-black">Cars</h3>
              </Link>
              <Link
                href="/admin/data/parts"
                className="cursor-pointer duration-150 ease-linear hover:scale-[1.2]"
              >
                <div className="relative mx-auto flex items-center justify-center">
                  <BuildIcon fontSize="large" />
                </div>
                <h3 className="mt-8 text-lg font-semibold text-black">Parts</h3>
              </Link>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Data;
