import { type NextPage } from "next";
import Head from "next/head";
import AddCar from "../../components/cars/AddCar";
import { trpc } from "../../utils/trpc";
import SortedTable from "../../components/tables/SortedTable";
import { useMemo, useState } from "react";

interface Data {
  make: string;
  model: string;
  series: string;
  generation: string;
}

const Cars: NextPage = () => {
  const [showModal, setShowModal] = useState(false);
  const [headCells, setHeadCells] = useState<readonly string[]>([]);
  const [rows, setRows] = useState<Data[]>([]);
  const cars = trpc.cars.getAll.useQuery();

  useMemo(() => {
    setHeadCells([]);
    setRows([]);
    if (!cars.data) return;
    setHeadCells((): any => {
      const cells = Object.keys(cars.data[0])
        .filter((key) => key !== "id")
        .map((key: any) => {
          return {
            disablePadding: false,
            id: key,
            numeric: false,
            label: key,
          };
        });
      return cells;
    });
    cars.data?.forEach((car) => {
      setRows((prev) => [...prev, car]);
    });
  }, [cars.data]);

  return (
    <>
      <Head>
        <title>Cars</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-white">
        {showModal ? (
          <AddCar showModal={showModal} setShowModal={setShowModal} />
        ) : null}
        <SortedTable headCells={headCells} rows={rows} title="Cars" />
      </main>
    </>
  );
};
export default Cars;
