import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import AddCar from "../../components/cars/AddCar";
import React from "react";

import { trpc } from "../../utils/trpc";

const Cars: NextPage = () => {
  const [showModal, setShowModal] = React.useState(false);

  return (
    <>
      <Head>
        <title>Cars</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        {showModal ? (
          <AddCar showModal={showModal} setShowModal={setShowModal} />
        ) : null}
        <button onClick={() => setShowModal(!showModal) as any}>Add car</button>
        <div className="flex h-full w-[75%]">
          <div className="flex w-[50%] flex-col"></div>
          <div className="w-[50%]">Details</div>
        </div>
      </main>
    </>
  );
};

export default Cars;
