import { type NextPage } from "next";
import Head from "next/head";
import AddCar from "../../components/cars/AddCar";
import { trpc } from "../../utils/trpc";
import SortedTable from "../../components/tables/SortedTable";
import { useMemo, useState } from "react";
import { Car } from "@prisma/client";

const Cars: NextPage = () => {
  const [showModal, setShowModal] = useState(false);
  const [headCells, setHeadCells] = useState<readonly string[]>([]);
  const [rows, setRows] = useState<Car[]>([]);
  const cars = trpc.cars.getAll.useQuery(
    {},
    {
      onSuccess: (data) => {
        setHeadCells([]);
        setRows([]);
        setHeadCells((): any => {
          const cells = Object.keys(data[0] as Car)
            .filter((key) => key !== "id")
            .map((key: any) => {
              return {
                disablePadding: false,
                id: key,
                numeric: false,
                label: key,
              };
            });
          return cells;
        });
        data?.forEach((car) => {
          setRows((prev) => [...prev, car]);
        });
      },
    }
  );

  return (
    <>
      <Head>
        <title>Cars</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-white">
        {showModal ? (
          <AddCar showModal={showModal} setShowModal={setShowModal} />
        ) : null}
        <SortedTable
          headCells={headCells}
          rows={rows}
          title="Cars"
          setShowModal={setShowModal}
        />
      </main>
    </>
  );
};
export default Cars;
