import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import TimeToLeaveIcon from "@mui/icons-material/TimeToLeave";
import CarRepairIcon from "@mui/icons-material/CarRepair";
import BuildIcon from "@mui/icons-material/Build";
import SellIcon from "@mui/icons-material/Sell";

const Admin: NextPage = () => {
  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex w-full justify-center items-center">
        <section className="bg-white w-full py-10 sm:py-16 lg:py-24">
          <div className="mx-auto w-[50%] px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 gap-12 text-center sm:grid-cols-2 md:grid-cols-2 lg:gap-y-16">
              <Link
                href="/admin/cars"
                className="cursor-pointer w-full duration-150 ease-linear hover:scale-[1.2]"
              >
                <div className="relative mx-auto flex items-center justify-center">
                  <TimeToLeaveIcon className="text-7xl" />
                </div>
                <h3 className="mt-8 text-lg font-semibold text-black">Cars</h3>
              </Link>
              <Link
                href="/admin/donors"
                className="cursor-pointer duration-150 ease-linear hover:scale-[1.2]"
              >
                <div className="relative mx-auto flex items-center justify-center">
                  <CarRepairIcon className="text-7xl" />
                </div>
                <h3 className="mt-8 text-lg font-semibold text-black">
                  Donors
                </h3>
              </Link>
              <Link
                href="/admin/parts"
                className="cursor-pointer duration-150 ease-linear hover:scale-[1.2]"
              >
                <div className="relative mx-auto flex items-center justify-center">
                  <BuildIcon className="text-7xl" />
                </div>
                <h3 className="mt-8 text-lg font-semibold text-black">Parts</h3>
              </Link>
              <Link
                href="/admin/listings"
                className="cursor-pointer duration-150 ease-linear hover:scale-[1.2]"
              >
                <div className="relative mx-auto flex items-center justify-center">
                  <SellIcon className="text-7xl" />
                </div>
                <h3 className="mt-8 text-lg font-semibold text-black">
                  Listings
                </h3>
              </Link>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Admin;
