import { type NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useMemo, useState } from "react";
import { trpc } from "../../utils/trpc";
import AddOrigin from "../../components/origins/AddOrigin";
import SortedTable from "../../components/tables/SortedTable";
import { Origin } from "@prisma/client";
import { Car } from "@prisma/client";

const Origins: NextPage = () => {
  const [showModal, setShowModal] = React.useState(false);
  const [headCells, setHeadCells] = useState<readonly string[]>([]);
  const [rows, setRows] = useState<Origin[]>([]);
  const origins = trpc.origins.getAllDashboard.useQuery();

  useMemo(() => {
    setHeadCells([]);
    setRows([]);
    if (!origins.data) return;
    const hideColumns = ["updatedAt", "Part", "car"]
    const nestedColumns = [{ car: ["series", "generation", "model"] }]
    setHeadCells((): any => {
      const cells = Object.keys(origins.data[0] as any)
        .filter((key) => {
          if (hideColumns.includes(key)) return false;
          if (nestedColumns[key]) return false;
          return true;
        })
        .map((key: any) => {
            return {
              disablePadding: false,
              id: key,
              numeric: false,
              label: key,
            };
        })
      nestedColumns.forEach((nestedColumn) => {
        Object.values(nestedColumn).forEach((nestedColumnValue) => {
          nestedColumnValue.forEach((nestedColumnValueValue) => {
            cells.splice(cells.indexOf("year")-1, 0, {
              disablePadding: false,
              id: nestedColumnValueValue,
              numeric: false,
              label: nestedColumnValueValue,
              });
          });
        }
        );
      })
      return cells;
    });
    const newRows = origins.data?.map((origin) => {
      return {
        vin: origin.vin,
        year: origin.year,
        cost: origin.cost,
        createdAt: new Date(origin.createdAt).toLocaleDateString(),
        series: origin.car.series,
        generation: origin.car.generation,
        model: origin.car.model,
        totalListedParts: origin.Part.reduce((acc,cur) => acc + cur.price, 0)
      };
    });
    setRows(newRows);
  }, [origins.data]);

  useEffect(() => {
    console.log(rows)
  }, [rows])

  return (
    <>
      <Head>
        <title>Origins</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-white">
        {showModal ? (
          <AddOrigin showModal={showModal} setShowModal={setShowModal} />
        ) : null}
        <div>
          <button onClick={() => setShowModal(!showModal)}>Add Origin</button>
        </div>
        <SortedTable headCells={headCells} rows={rows} title={"Origins"} rowId={"vin"} />
      </main>
    </>
  );
};

export default Origins;
