import { type NextPage } from "next";
import Head from "next/head";
import React, { useMemo, useState } from "react";
import { trpc } from "../../utils/trpc";
import AddOrigin from "../../components/origins/AddOrigin";
import SortedTable from "../../components/tables/SortedTable";
import { Origin } from "@prisma/client";
import { Car } from "@prisma/client";

const Origins: NextPage = () => {
  const [showModal, setShowModal] = React.useState(false);
  const [headCells, setHeadCells] = useState<readonly string[]>([]);
  const [rows, setRows] = useState<Origin[]>([]);
  const origins = trpc.origins.getAllDashboard.useQuery();

  useMemo(() => {
    setHeadCells([]);
    setRows([]);
    console.log(origins.data)
    if (!origins.data) return;
    const hideColumns = ["Part", "createdAt"]
    setHeadCells((): any => {
      const cells = Object.keys(origins.data[0] as any)
        .filter((key) => {
          if (hideColumns.includes(key)) return false;
          return true;
        })
        .map((key: any) => {
          if (typeof origins.data[0][key] === "object") {

          }
            return {
              disablePadding: false,
              id: key,
              numeric: false,
              label: key,
            };
        });
      console.log(cells)
      // insert cells series generation and model after the year cell
      return cells;
    });
    const newRows = origins.data?.map((origin) => {
      return {
        vin: origin.vin,
        year: origin.year,
        cost: origin.cost,
        createdAt: new Date(origin.createdAt).toLocaleDateString(),
        series: origin.car.series,
        generation: origin.car.generation,
        model: origin.car.model,
      };
    });
    setRows(newRows);
  }, [origins.data]);

  return (
    <>
      <Head>
        <title>Origins</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-white">
        {showModal ? (
          <AddOrigin showModal={showModal} setShowModal={setShowModal} />
        ) : null}
        <div>
          <button onClick={() => setShowModal(!showModal)}>Add Origin</button>
        </div>
        <SortedTable headCells={headCells} rows={rows} title={"Origins"} rowId={"vin"} />
      </main>
    </>
  );
};

export default Origins;
